trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- bash: npm install
  displayName: 'Install dependencies'
- bash: npm run build
  displayName: 'Build'


